import { useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";


export default function Home() {


  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const kiubo = api.example.greeting.useQuery({ name:"Plebe"})

 const { user }  = useUser()

 
  console.log("Kiubo")
 console.log(kiubo.data)
 
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <div className={styles.cardRow}>
        


          </div>
          <p className={styles.showcaseText}>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
